### ISSUE TITLE
$.live() funtion not any longer supported in jQuery >= 1.9

### ISSUE THREAD

**Issue by CC1337** [vast-engineering/jquery-popup-overlay#1]
jquery-popup-overlay won't work with new jQuery versions because $.live() function, used in line 168, is not available anymore and should be replaced by $.on() function. See http://stackoverflow.com/questions/14354040/jquery-1-9-live-is-not-a-function.

**Comment by mfbx9da4** [comment]
Its line 186 I believe

**Comment by panthershark** [comment]
If you create a pull request, we'll merge it.  

Thanks

**Comment by lucianosousa** [comment]
same problem.
fixed here: https://github.com/vast-eng/jquery-popup-overlay/pull/7

**Comment by vladimirsiljkovic** [comment]
Pull request by @lucianosousa is merged. Thank you all.
