### ISSUE TITLE
onopen and onclose not working

### ISSUE THREAD

**Issue by whwright** [vast-engineering/jquery-popup-overlay#10]
I cannot get the opopen and onclose to work, but beforeopen works fine. Is there anything wrong with this:

  $('#my_modal').popup({
    onopen : function() {
    },
    onclose : function() {
    },
        beforeopen : function() {
        }
    }); 

EDIT:
I apologize, the documentation doesn't match it is is onOpen and onClose. I didn't see the other issue.

**Comment by vladimirsiljkovic** [comment]
Thanks for reporting, @wright8191. This is fixed now with the commit for https://github.com/vast-eng/jquery-popup-overlay/issues/3
