### ISSUE TITLE
using on more than one element on a page

### ISSUE THREAD

**Issue by jjb** [vast-engineering/jquery-popup-overlay#11]
it seems the library isn't well-suited for using on more than one element per page. to achieve this i have to make a numbered class for each element, and generate instantiation javascript for each element as well. like this:

``` html
<button class='foo_modal_25_open'>
  click to see the things for item 25
</button>
<div id='foo_modal_25'>
  here are the things for item 25
  <button class='foo_modal_25_close'>Close</button>
</div>
<script>
  $(function() {
    $('#foo_modal_25').popup();
  });
</script>
```

Is there a better way to achieve this?

**Comment by makingthingswork** [comment]
Yeah that was one of the first things I looked for myself, this is a very good popup but its inability to handle multiple elements on one page without having to initialise every popup individually is a bit of a drawback. Even if you use an each loop to go through all the buttons and grab the IDs you'd still have to use that ID and call .popup() for every ID you find.

All that said I'm still going to use it as other popups I've found with fade and scale have far too much code plus this one work well on all devices.

**Comment by vladimirsiljkovic** [comment]
There is a way to make multiple modals on the page with a single popup container, and a single javascript  plugin call, using `onopen` callback. I've made a simple image gallery to demonstrate that:

http://jsfiddle.net/M5Pe6/4/

I'm not sure what exactly you are trying to achieve and what is your scenario. Are you creating popups or links dynamically? Do you need a single popup container for multiple links,

Can you link some library that do have the functionality that you need so we can take a look and see if we can implement some of that to enhance our plugin.

Thanks!

**Comment by vladimirsiljkovic** [comment]
Also, we will soon add a demo popup using AJAX to populate content of the popup and add it to other examples. 

We still need to test this and maybe enhance the plugin for AJAX usage.

**Comment by makingthingswork** [comment]
Great news that you are adding AJAX functionality but for now your example is perfect for what I was wanting to do, excellent thanks

**Comment by crossidia** [comment]
multiple modals with a single popup container: great !! it works with pictures but when you substitute the url of a picture  with the url of a video (in youtube for instance) it doesn't work ... is there a way to make it work ? 
And last question .... how can i see the next picture in the same pop up window  without exit from the pop up,  just clicking on the picture (like facebook and vk gallery) ??
Thanks a lot for help

**Comment by vladimirsiljkovic** [comment]
Hi @crossidia,

You can't just change a URL of an `<img>` element with a video, because video needs a different markup. We will add an example with a single (Youtube, Vimeo, HTML5) video inside of a popup to our demo page soon.

This plugin doesn't provide image or video gallery functionality out of the box for now, and I'm not sure if it ever will. However, you can combine it with some other image gallery library, and then place the HTML for the gallery inside of a popup.

I can recommend these plugins which have image gallery integrated: 
http://dimsemenov.com/plugins/magnific-popup/
http://lab.veno.it/venobox/

As for your last question, you'll need additional custom javascript or external image gallery library for that.

Thanks.

**Comment by crossidia** [comment]
Thank you so much.
I appreciated your raccomandations. I will test the plugins you adviced me.
Ciao

2014-11-10 18:27 GMT+01:00 Vladimir Siljkovic notifications@github.com:
