### ISSUE TITLE
How to produce slide effect?

### ISSUE THREAD

**Issue by sackIndian** [vast-engineering/jquery-popup-overlay#13]
Hi,
Is there any way to produce slide effect while showing models?

**Comment by vladimirsiljkovic** [comment]
It's possible with the new version of the plugin (v1.6.0). Here's the example: http://jsfiddle.net/9z8r5/2/ You can also change vertical align to be top if needed,  by setting `vertical` option to `top`. Further tweaks are possible with CSS.

Also, take a look at "Slide in" example on the demo page: http://vast-eng.github.io/jquery-popup-overlay/#basic

Hope it helps.

Thanks!

**Comment by vladimirsiljkovic** [comment]
If you need a slide from left, bottom, or right, you just need to modify CSS a bit (`translateX` and `translateY`).

For further inspiration take a look at http://tympanus.net/Development/ModalWindowEffects/
