### ISSUE TITLE
Click overlay to close doesn't work on iPad/iPhone

### ISSUE THREAD

**Issue by makingthingswork** [vast-engineering/jquery-popup-overlay#14]
If you elect not to have a close button for design purposes then you cannot close the popup by clicking on the overlay when on iOS. 

Is there a solution for this? Of course I could do a iOS only close button that doesn't show on the web version.

**Comment by vladimirsiljkovic** [comment]
Thanks for reporting, @makingthingswork.

You are correct, this will be fixed soon. We need to register additional `touchstart` event besides a regular `click` event for closing the popup.

Thanks.

**Comment by chandanonline4u** [comment]
Check if device browser support touchstart event and then register additional touchstart event for closing the popup. For more information see http://www.chandankumar.in/fix-jquery-popup-overlay-close-issue-on-ipad-iphone/

**Comment by vladimirsiljkovic** [comment]
This should be fixed now. Thank you both!

We can add a custom option like "closeontouch" in the future if needed.

@makingthingswork You can also add a closing button as well that will be visible both for desktop and mobile devices. Closing buttons should be working fine in both cases.
