### ISSUE TITLE
Close overlay?

### ISSUE THREAD

**Issue by likentong** [vast-engineering/jquery-popup-overlay#2]
Hi, is there a way to close the overlay using jquery? A function that i can close like "popupclose()";

**Comment by marko-jankovic** [comment]
Yes, you have to add suffix "-close" to class name (class="my_modal-close")

Please, see example on http://vast-eng.github.io/jquery-popup-overlay/

**Comment by barrybar2** [comment]
It's supposed to be '_close' not '-close'. It's a mistake on the example. (class="my_modal_close")

**Comment by rthewhite** [comment]
For anyone that is experiencing this issue. When you open the popup using the popup function.
That functions returns the internal hidePopUp function, call that function with the DOM element of the popup and it will get closed.

Example:

```
var $dialog = $( ".someSelectorToYourDialog" );
var closeDialog = $dialog.popup( { autoopen: true, keepfocus: false } );

closeDialog( $dialog[ 0 ] );
```

The hidePopUp function expects an DOM element and not a jquery object. If you pass an jQuery object ( $dialog in this case ), the popup will be closed but the background stays visible. [ 0 ] grabs the native DOM element for you :-)

**Comment by vladimirsiljkovic** [comment]
Now there's a method for closing a popup. Here's an example:

```
$('#my_popup').popup('hide');
```

More information on the demo page: http://vast-eng.github.io/jquery-popup-overlay/

Hope this solves this issue. If it doesn't – please reopen.

Thanks.
