### ISSUE TITLE
Mobile Issues

### ISSUE THREAD

**Issue by chmoore** [vast-engineering/jquery-popup-overlay#22]
We are unable to swipe to scroll content on touch devices within the popup overlay. It scrolls fine on desktop browsers and content that exceeds the screen height will display a scrollbar but will not move on mobile. We've tried everything within our build before using one of the demos and finding it also has the same issue.

**Comment by vladimirsiljkovic** [comment]
Hi chmoore,

I can't reproduce the issue on multiple iOS and Android devices.

Which browser / OS / device / plugin version are you using?

Thanks!

**Comment by vladimirsiljkovic** [comment]
Closing this one. The issue was reproducible on very old Android devices that don't support `position:fixed`.
