### ISSUE TITLE
How to use without a button ? Just only with an activated trigger

### ISSUE THREAD

**Issue by damienvaz** [vast-engineering/jquery-popup-overlay#23]
Hello,
I saw your popups buttons and i really appreciate it !
But i have one question ! Is it possible to use these popups without a button ? 
What i want to do it's:

```
    $(".responsive-calendar").responsiveCalendar({
            time: '2013-04',
            events: {
            "2013-04-30": {"number" : 2, "value" :"Hello Marina"},
            "2013-04-26": {}, 
            "2013-05-03": {}, 
            "2013-06-12": {}},
            onActiveDayClick: function(events) {
                var thisDayEvent, key;

                key = $(this).data('year')+'-'+addLeadingZero( $(this).data('month') )+'-'+addLeadingZero( $(this).data('day') );
                thisDayEvent = events[key];

                $().popup({
                    autoopen : true,
                    transition: 'all 0.3s'
                });
            }
        });
  });
```

when "onActiveDayClick" is activated, popup message should show me the message and do the effect !
Is that possible ? Thankfully

**Comment by damienvaz** [comment]
Nevermind ... I added a modal bootstrap for a nicer popup message instead of alert ! 
Basically i added some info on your .js file :P
If you want, feel free to ask me !

**Comment by vladimirsiljkovic** [comment]
Hi Demien,

Glad you find a solution.

Popup can be automatically opened with either `autoopen` option:

```
$('.responsive-calendar').popup({autoopen: true})
```

...or `show` method:

```
$('.responsive-calendar').popup('show')
```

**Comment by damienvaz** [comment]
do you only use an alert ?
