### ISSUE TITLE
Scrolllock doesn't release on closure

### ISSUE THREAD

**Issue by PaparazzoKid** [vast-engineering/jquery-popup-overlay#25]
Using jQuery 2.1.0, I have found that using the 'scrollock' feature to prevent the main content scrolling during the use of a popup, is failing. When the popup opens, scrolling has been disabled as it should, but when the popup closes the scrolling is still disabled, making the website hard to navigate until page refresh.

**Comment by vladimirsiljkovic** [comment]
This should be fixed now.

Thanks for reporting, @PaparazzoKid.
