### ISSUE TITLE
onopen and onclose callbacks do not match documentation

### ISSUE THREAD

**Issue by jeffhunt00** [vast-engineering/jquery-popup-overlay#3]
The documentation at http://vast-eng.github.io/jquery-popup-overlay/ notes callbacks for 'onopen' and 'onclose' in all lowercase , but in the js (on lines 356 and 460, respectively) they use mixedCase, ie: 'onOpen' and 'onClose'. 'beforeclose' correctly uses lowercase in the docs and the code.

At minimum the docs should match the code, and the three callbacks should likely all have a  matching use of case, probably lowercase.

**Comment by vladimirsiljkovic** [comment]
Hi @jeffhunt00,

Thanks for reporting. This should be fixed now, I've updated the documentation to match the code.

I've left camel case in order not to break the existing code but we will standardize callback names in 2.0 version which is under way.

**Comment by vladimirsiljkovic** [comment]
Actually, I've changed 'onOpen' and 'onClose' to use lower case in order to be consistent with other callbacks (such as 'beforeopen'), and updated the docs accordingly.

Thanks again!
