### ISSUE TITLE
Uncaught TypeError: Cannot read property 'blur' of undefined

### ISSUE THREAD

**Issue by versum** [vast-engineering/jquery-popup-overlay#30]
In my error reporting tool I have a lot of errors like:
Uncaught TypeError: Cannot read property 'blur' of undefined (line 625)
Uncaught TypeError: Cannot read property 'keepfocus' of undefined (line 664)

I couldn't reproduce this myself but you should consider adding a check to make sure that $(el).data('popupoptions') is not null.
You could also add a namespace to event bindings like click and keydown so that i could use off() function on them as I do not use those options.

**Comment by vladimirsiljkovic** [comment]
Fixed in #70. Thanks for reporting, @ghost.
