### ISSUE TITLE
IE7 throws JS error

### ISSUE THREAD

**Issue by ajpeacock** [vast-engineering/jquery-popup-overlay#37]
IE7 throws Expected identifier, string or number Javascript Error.

**Comment by vladimirsiljkovic** [comment]
Thank you, @ajpeacock.

Also, if you need to fully support IE7, this additional CSS is required (because IE7 doesn't understand `display: inline-block;`):

```
.popup_content,
.popup_align {
    *display: inline !important;
    *zoom: 1;
}
```
