### ISSUE TITLE
z-index and multiple popup instances

### ISSUE THREAD

**Issue by hlecorche** [vast-engineering/jquery-popup-overlay#41]
There is a bug with z-index when there are multiple popup instances.

In this code (http://jsfiddle.net/3t74x6v0/3/), my_popup2 is initialized before my_popup and my_popup2 (yellow popup) is above my_popup (red popup)

In this code (http://jsfiddle.net/3t74x6v0/4/) my_popup2 is initialized after my_popup and my_popup2 (yellow popup) is under my_popup (red popup). Is this behavior normal? Why?

**Comment by vladimirsiljkovic** [comment]
Thanks for reporting. Fixed in v2.1.0 (14b77ea).

The issue was reproducible on pages that had no z-index set on any element on the page, so the maximum z-index was 0.
