### ISSUE TITLE
Why backgroundactive removes vertical centering?

### ISSUE THREAD

**Issue by diaspar** [vast-engineering/jquery-popup-overlay#43]
When using this option:

backgroundactive

The overlay no longer stays vertically centered with multiple sizes, it stays fixed. Is this by design or there is something else we should do?

**Comment by darylldawn** [comment]
I have the same concern. Please update if you can. Thanks.

**Comment by SynapsisIT** [comment]
Same here, when adding `backgroundactive:true` to lets say a standalone version, the #standalone_background disappears and #standalone_wrapper changes height from 100% to 0px.

**Comment by vladimirsiljkovic** [comment]
Hi, thanks for reporting and sorry for the delay.

This should be fixed on v2.0.1.

`backgroundactive` option was removed in version 2.0.1 but you can achieve the same effect with `{background:false, absolute:true, blur:false}`.

Here's a demo https://codepen.io/anon/pen/EGawMr . 
New examples are added to the demo page as well https://dev.vast.com/jquery-popup-overlay/ .
