### ISSUE TITLE
Popup not working in infinite scroll.

### ISSUE THREAD

**Issue by sevekim** [vast-engineering/jquery-popup-overlay#55]
Hi, so here is a demo site which you will see the red button at the end of each post.

http://sevek.staging.wpengine.com/

I am using the popup overlay for the each button.

When you first scroll all the way to the bottom, more contents will be loaded via infnite scroll. 

However the second section that is loaded after the infinite scroll simply does not work.

I can see that the elements are still there, but nothing is being triggered.

Could you look into it?

Thank.

Steve

**Comment by FilipLaz** [comment]
Hey Steve, 

Your javascript code is the problem, here you initialize the popup for every\* .rh_purchase_button button,

``` javascript
jQuery(".rh_purchase_button").click(function(){
    var product_id_edit = jQuery(this).data("post_id");
    jQuery('#rh_purchase_' + product_id_edit).popup();
});
```

*but "every" .rh_purchase_button button available in the DOM at the DOM ready event.

You need to delegate the handler that would open the popup, for example like this:

``` javascript
jQuery("body").on("click", ".rh_purchase_button", function() {
    var product_id_edit = jQuery(this).data("post_id");
    jQuery('#rh_purchase_' + product_id_edit).popup();
})
```

You can find more about this topic on official jQuery documentation,
http://api.jquery.com/on/

Also take a good look there, you will find details how to improve the snippet I have posted.

**Comment by sevekim** [comment]
Thank you for the reply.

So, now the popup overlay works. However the content within seems like it does not work.

For example, I changed to "<div class="rh_contact_spinner mdl-spinner mdl-js-spinner is-active"></div>  to show a spinning wheel when you click the button now.

The first section shows the spinning wheel. However with the second section, it simply shows "loading" and nothing else.

What could be causing this?

I will definitely read it. 

Thanks
