### ISSUE TITLE
addclosebutton throws error

### ISSUE THREAD

**Issue by jonsquared** [vast-engineering/jquery-popup-overlay#56]
When specifying closebutton: true in the config, the addclosebutton will throw an error trying to reference $el

**Comment by vladimirsiljkovic** [comment]
Sorry for the long delay.

I couldn't reproduce this. Here's a working demo: https://codepen.io/anon/pen/LMEOEY

Please reopen if the issue is still reproducible, with a demo or options if possible. Thanks.
