### ISSUE TITLE
scroll lock not working when i use iphone6 in safari

### ISSUE THREAD

**Issue by ghokyo** [vast-engineering/jquery-popup-overlay#57]
Thank you for make source :+1: 

When i open a iphone(safari), the scroll lock function is not working...
but i open a android(chrome) phone is working..

i'm use fade popup source and scrolllock function 

Could you tell me how can fix it?

**Comment by gintechsystems** [comment]
@ghokyo 

A simple fix is to add the following code where needed in the script using jQuery, just search for options.scrolllock:

`$body.on('touchmove', function(e){
                     e.preventDefault();
                });`

`$body.off('touchmove');`

**Comment by vladimirsiljkovic** [comment]
This is fixed in iOS Safari 13 https://bugs.webkit.org/show_bug.cgi?id=153852
