### ISSUE TITLE
Two popup layers

### ISSUE THREAD

**Issue by sevekim** [vast-engineering/jquery-popup-overlay#59]
I have a popup within another popup, but of course only the first layer is shown.

Here is the current set up that I have:

```
<div class="rhmb_right rhhouse">
    <button type="button" class="first_popup_open" >
       First popup
    </button>
        <div id="first_popup" style="display:none;">
           <button type="button" class="second_popup_open" >
              Second
           </button>
           <div id="second_popup" style="display:none;">
               Second popup works!
           </div>
       </div>
</div>
<script>  
$(document).ready(function() { 
    $('#first_popup').popup();
    $('#second_popup').popup();                             
    }); 
</script>
```

So, both popup seems to work. However, the first layer is always on top of the second one (ie. can't see the second popup content, but I know it works because I can see the background changes). I tried z-index, but no result.

Does anyone know how to fix this?

Thanks!

**Comment by vladimirsiljkovic** [comment]
Can you try to add option `autozindex: true` to the second popup?

```
 $('#second_popup').popup({ autozindex: true });
```

If that doesn't work, please provide a JSBin demo.

Thanks.

**Comment by sevekim** [comment]
Thanks! It worked! =)
