### ISSUE TITLE
Wrong paramter passed to 'beforeopen' callback

### ISSUE THREAD

**Issue by niedzwiedzislaw** [vast-engineering/jquery-popup-overlay#6]
For modal named _Modal_ paramater with selector _.Modal_wrapper_open[data-popup-order="0"]_ is passed. Because of this the source of the opening event is not accessible. Similar issue may affect other callbacks.

**Comment by vladimirsiljkovic** [comment]
Fixed with https://github.com/vast-eng/jquery-popup-overlay/commit/5df10cd09b57be9e859979ab5f60e5d075b15457

Thanks for reporting, @ghaxx.
