### ISSUE TITLE
Call fct from iframe

### ISSUE THREAD

**Issue by Razorholt** [vast-engineering/jquery-popup-overlay#66]
First of, great code!

I'm trying to open the popup in parent from an iframe. Here is a sample of the code in the iframe:

``` javascript
$(function() {
    $('#button').on('click', function(e) {
        window.parent.$("#mypopup").popup();
    });
});
```
Is there a solution for that? Thanks!

**Comment by zivanovica** [comment]
@Razorholt to do that, you'll need to [communicate between documents](http://stackoverflow.com/questions/9153445/how-to-communicate-between-iframe-and-the-parent-site).

To show popup you will just need to trigger it in `window.onmessage` callback.
