### ISSUE TITLE
Request: Disable background click close

### ISSUE THREAD

**Issue by embluk** [vast-engineering/jquery-popup-overlay#69]
I've looked to see if this does exist and I can't find it?

Basically have an extra option to choose if the background can close the popup or not, this then only allows me to use a button to close the popup.

**Comment by vladimirsiljkovic** [comment]
Hi @embluk,

There's an option `blur` (boolean, true, closes the popup when clicked outside of it). Perhaps we should update the docs to make it more clear.

**Comment by embluk** [comment]
Arrh sorry to waste time, yeah I guess it just wasn't as clear for me. Thanks, I found it and it works as expected.

Keep up the good work!

**Comment by vladimirsiljkovic** [comment]
Thanks! I'm glad it worked.
