### ISSUE TITLE
a question please

### ISSUE THREAD

**Issue by scratchoo** [vast-engineering/jquery-popup-overlay#71]
Hi, thank you for the awesome plugin, and sorry to post this here because I haven't found any way to contact you... can you please tell me what you did to keep the modal+overlay scroll within the page on mobile devices, I have my own popup but on mobile if I scroll the overlay and the modal stay at the top ! thanks

**Comment by vladimirsiljkovic** [comment]
Hi @medBouzid, 

`position: fixed;` with `overflow: auto;` is being used for the popup overlay. That prevents the popup from scrolling with the rest of the page and enables scrolling inside of the popup. If you share a link to your demo page it would give a better insight.

Thanks

**Comment by scratchoo** [comment]
Hi @vladimirsiljkovic ,

Thanks you for your reply, I added `position: fixed;` and `overflow: auto;` to the overlay but the problem still there, if you scroll down on mobile the overlay with the popup stay at the top half of the page, here is the link : https://somegrammar.com/popup/ there is a button at the top that shows the popup

Thanks in advance

**Comment by scratchoo** [comment]
I tried to use your plugin in my web page and with the "basic" animation, when I scroll on mobile the popup+overlay stay at the top and the content get scrolled, I noticed that "slide" animation is working good on my mobile and do the needed effect so I dig in its css and I added this to the page when I use "basic" : 

```
#basic_background {

            -webkit-transition: all 0.3s 0.3s;
               -moz-transition: all 0.3s 0.3s;
                    transition: all 0.3s 0.3s;
        }

        
        #basic,
        #basic_wrapper {

            -webkit-transition: all 0.4s;
               -moz-transition: all 0.4s;
                    transition: all 0.4s;
        }

        
        #basic {
            background: white;
           -webkit-transform: translateX(0) translateY(0);
               -moz-transform: translateX(0) translateY(0);
                -ms-transform: translateX(0) translateY(0);
                    transform: translateX(0) translateY(0);
        }
```

I don't know why but this code make the "basic" popup work correctly on my mobile, so I tried to apply this to my own popup but it doesn't work !! I am not sure if there is something in the js part that have some effect on that ! any help please ?

**Comment by vladimirsiljkovic** [comment]
I think this is what you need: http://jsbin.com/fedebasema/edit?html,css,output

The difference is the way the popup is centered – you've used `transform`, while we've used `vertical-align` and `text-align`.  The changes are marked with comments.
