### ISSUE TITLE
Vertical Alignment Not Functioning

### ISSUE THREAD

**Issue by YourTechWhiz** [vast-engineering/jquery-popup-overlay#76]
When I'm trying to align the pop-up to the top-right of the window, I set the horizontal to 'right' and vertical to 'top'. The horizontal alignment works fine, but the vertical alignment doesn't seem to do anything. I've also tried 'bottom' as well to see if it changed but nothing happened.

**Comment by vladimirsiljkovic** [comment]
Hi @YourTechWhiz, thanks for reporting.

I was able to reproduce this with only with `backgroundactive` set to `true`.

`backgroundactive` option was removed in version 2.0.1 but you can achieve the same effect with `background: false, absolute: true, blur: false`.

It should work fine with these options. Here's a demo https://codepen.io/anon/pen/roaGzd and  another example is added to the demo page https://dev.vast.com/jquery-popup-overlay/ (see "Active bg absolute" example).
