### ISSUE TITLE
Prevent overlay close

### ISSUE THREAD

**Issue by howardowens** [vast-engineering/jquery-popup-overlay#78]
This is more of a support question.

Currently, this is working for me:

`$('#my_popup').popup('show').load("subs.html");`

To keep escape from closing the overlay, I've tried 

`$('#my_popup').popup('show', {escape: false}).load("subs.html");`

and

`   $.fn.popup.defaults.escape = 'false';`

but that would, if it worked, only gets me halfway there.  A click on the page also closes the overlay.  

I need to disable the ability to close the overlay both with escape and click outside the overlay.  How do I do that?

**Comment by pvgoran** [comment]
You can add `blur: false` to options, this should prevent overlay from being closed when clicking outside of it.

**Comment by mrbrimm** [comment]
Curiosity has me. Why would you want to do that?  I speak from an ada perspective which is sometimes a go to for escaping an overlay.   Simply curiosity.  Good luck!

**Comment by howardowens** [comment]
`$('#my_popup').popup('show', {blur: false}).load("subscriptions.html");`

Didn't work.

mrbrimm: This is for a mobile app that will require a subscription for some content, so the overlay needs to be binary, either click the button to subscribe or click the link to return to the home page.  Being able to close it would defeat the purpose, allowing users to read the story without subscribing.

**Comment by pvgoran** [comment]
Probably options can't be passed as a second parameter. You need something like this:

`$('#my_popup').popup({ escape: false, blur: false, autoopen: true })`

**Comment by howardowens** [comment]
@pvgoran +1

That did the trick.  Thanks.

**Comment by mrbrimm** [comment]
Aha!
