### ISSUE TITLE
Popups flashing on page load.

### ISSUE THREAD

**Issue by derjp** [vast-engineering/jquery-popup-overlay#79]
Every time I switch a page on my site the popups flash for a split second. I think that is because initially they are visible but they hide once the jquery or popup-overlay file loads. How can I prevent this behaviour?

**Comment by pvgoran** [comment]
Well, make them initially invisible, with `style="display: none;"`. Works like a charm. :)

**Comment by derjp** [comment]
Well, that was easy.. :D thanks

**Comment by wilsontse88** [comment]
But I tried that it also flash for a split second in mobile chrome browser even I set the popdiv is display: none  ....

then any other idea for solving this issue?

**Comment by pvgoran** [comment]
Please provide an example page that exhibits this behaviour.

**Comment by wilsontse88** [comment]
http://dev.vast.com/jquery-popup-overlay/

I used iphone / Chrome to view the demo page. And it appears the flash for a split second.

**Comment by wilsontse88** [comment]
why close this??

actually this is abnormal in iphone browser....

DerJP  how did u solve it?
