### ISSUE TITLE
how to stop video overlay popup completely when it is close

### ISSUE THREAD

**Issue by ayulayol** [vast-engineering/jquery-popup-overlay#80]
i have created video overlay popup on
http://ayulayol.html-5.me/sponsor/overlaypopupads.html

when i close the overlay the video is still loading in the background. how can i stop the video completely. thank you in advance

**Comment by pvgoran** [comment]
I think you need to delete the entire `<iframe>` in response to the `onclose` event.

**Comment by ayulayol** [comment]
how to do that? do you have the code? so i can changed it i want the iframe to be the video ads.

**Comment by pvgoran** [comment]
These are basic Javascript/jquery operations. See http://api.jquery.com/remove/ about element removal, http://dev.vast.com/jquery-popup-overlay/ (section "Callback events") about responding to events.

**Comment by ayulayol** [comment]
finally it works i have put some additional code that i found on the internet:

$('#standalone').popup({
  onclose: function() {
$("#myiframe").attr("src", "");
  }
});

to make the iframe with blank file. thank you.

**Comment by vladimirsiljkovic** [comment]
Another option would be to use `detach:true` plugin option, which would remove iframe from the DOM after closing the popup. That would be an equivalent for stopping the video (not pausing).

Also, for YouTube videos, you can use YouTube Player API to pause (or stop) the video on `onclose` plugin's event, and similar can be done for HTML5 &lt;video&gt; embeds. 

```
onclose: function () {
  // Using YouTube API. `?enablejsapi=1` needs to be added to the iframe src
  $('.embed-iframe').each(function(){
    this.contentWindow.postMessage('{"event":"command","func":"pauseVideo","args":""}', '*');
  });

  // Using HTML5 <video>
  // $("video").each(function() {
  //   this.pause()
  // });
}
```


I've added this demo to the examples in our docs: https://output.jsbin.com/vatuheb/
