### ISSUE TITLE
SVG Shape for Button

### ISSUE THREAD

**Issue by michaelpfaff** [vast-engineering/jquery-popup-overlay#82]
First of all, thanks for the awesome code! 

I'm trying to figure out how to use an SVG shape for this section instead of a button: 

` 
  <button class="my_popup_open">Open popup</button>`

But, I can't figure it out. 

1. Is that even possible? 
2. If so, any help trying to figure it out? 

Thanks!

**Comment by pvgoran** [comment]
The jquery version used in the examples (1.8.2) doesn't seem to handle `<svg>` elements well. With the (now latest) jquery version 1.12.4, you just set `class="my_popup_open"` for your `<svg>`, and it works.

**Comment by michaelpfaff** [comment]
@pvgoran Thanks! I'll try changing the version!
