### ISSUE TITLE
Can't seem to get it working on IE11, is there support? 

### ISSUE THREAD

**Issue by greenscript** [vast-engineering/jquery-popup-overlay#84]
Error: SCRIPT438: Object doesn't support property or method 'popup'

**Comment by pvgoran** [comment]
The demo page (http://dev.vast.com/jquery-popup-overlay/) does work for me in IE11. I assume the problem is with the way you try use the plugin.

Please provide a sample page that doesn't work in IE11 but works in other browsers, so that your problem could be investigated further.
