### ISSUE TITLE
Popup is not showing up

### ISSUE THREAD

**Issue by donslund** [vast-engineering/jquery-popup-overlay#87]
Popup is not showing up.

This is my code:
<div id="my_popup">
				hep
			</div>

<script>
if (!jQuery) {
    console.log('jquery.popupoverlay - jQuery not defined.');
} else {
    console.log('jquery.popupoverlay - jQuery is defined.');
}
    $(document).ready(function() {

      // Initialize the plugin
      $('#my_popup').popup({
		  onopen: function() {
			alert('Popup just opened!');
		  }
		});

    });
</script>

Console tells me that jQuery is defined. No errors shown.

**Comment by pvgoran** [comment]
1. You need to specify `autoopen: true` in options to have the popup open right on creation.

2. Plain jquery (this is what you check with `if (!jQuery)`) is not enough for popups to work, you need to reference the jquery.popupoverlay script file in HTML.

3. When inserting code in messages, use the appropriate formatting (triple-backtick, see https://guides.github.com/features/mastering-markdown/ ), or else github garbles it, like it did with your code.

**Comment by donslund** [comment]
It was the autoopen: true, thanks.

Both 2 and 3 was okay all ready.
