### ISSUE TITLE
Re-open after close + close button conflicting with autozindex option

### ISSUE THREAD

**Issue by mor10** [vast-engineering/jquery-popup-overlay#9]
I have two issues that I can't seem to resolve:
1. When the modal window is closed, it will not re-open.
2. The close button as implemented in examples and documentation does not work

You can see a live example of issue 1 by clicking the large Check Availability button here: http://ciaobambino.com/hotel-review/beach-house-half-moon-bay/ 

Issue 2 seems to relate to the autozindex option. When the option is set to true the button with the following markup does not work:

```
<a href="#" class="my_modal_close">×</a>
```

When autozindex is set to false, it does work.

**Comment by vladimirsiljkovic** [comment]
Hi @mor10 ,

To fix the first issue, you should change class names to _availability-popup_open_ and _availability-popup_close_. Classes for opening and closing links must follow the ID of the popup wrapper ( in your case it's  #availability-popup).

We will revisit the way we implemented Open and Close links in the future to make it less confusing if possible.

The second issue was harder to fix from Firebug, but I've was able to get a new popup on your site working, so nothing should be wrong with the plugin itself. To get the new popup on your site working, try the following:

Add this HTML:

``` html
<a href="#" class="test_open">open</a>

<div id="test">popup
  <a href="#" class="test_close">close</a>
</div>
```

And paste this in the console:

``` js
jQuery('#test').popup({
    'autozindex': true
});
```

Hope this helps.

Thanks.
