### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by ghost** [vast-engineering/jquery-popup-overlay#92]
It happened when I clicked on the button.

Uncaught TypeError: Cannot read property 'left' of undefined
    at Object.reposition (jquery.popupoverlay.js:610)
    at Object.show (jquery.popupoverlay.js:380)
    at jquery.popupoverlay.js:230

**Comment by vladimirsiljkovic** [comment]
Hi @JackDarth,

It's best to make a demo on jsbin.com or elsewhere, so we can reproduce the issue.
